//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela.Types
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoMateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlumnoMateria()
        {
            this.Calificacion = new HashSet<Calificacion>();
        }
    
        public int idAlumnoMateria { get; set; }
        public int MateriaProfesor_idMateriaProfesor { get; set; }
        public string Alumno_boleta { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual MateriaProfesor MateriaProfesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacion { get; set; }
    }
}
