//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela.Types
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int idCalificacion { get; set; }
        public Nullable<double> Primer { get; set; }
        public Nullable<double> Segunda { get; set; }
        public Nullable<double> Tercera { get; set; }
        public int AlumnoMateria_idAlumnoMateria { get; set; }
    
        public virtual AlumnoMateria AlumnoMateria { get; set; }
    }
}
