//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela.Types
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class App_DataEntities : DbContext
    {
        public App_DataEntities()
            : base("name=App_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoMateria> AlumnoMateria { get; set; }
        public virtual DbSet<Calificacion> Calificacion { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<MateriaProfesor> MateriaProfesor { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<secRol> secRol { get; set; }
        public virtual DbSet<secUser> secUser { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
    }
}
